[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"
  base = "/"

[functions]
  node_bundler = "esbuild"
  [functions.timeout]
    duration = 30
  memory = 128
  max_concurrent_requests = 1
  max_idle_instances = 1
  runtime = "nodejs14"
  include = ["dist"]
  exclude = ["node_modules/**"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = false